//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppErrorLog
    {
        public long ErrorID { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<System.DateTime> datelog { get; set; }
        public string innerException { get; set; }
        public string stackTrace { get; set; }
    }
}
