//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFeaturedReferrence
    {
        public long ClientFeaturedReferrenceId { get; set; }
        public long userId { get; set; }
        public int categoryType { get; set; }
        public int featuredReferrenceValue { get; set; }
    }
}
