//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientWebInformation
    {
        public int ClientWebsiteInformationid { get; set; }
        public long userId { get; set; }
        public int themeId { get; set; }
        public int fontFamilyId { get; set; }
        public string logoName { get; set; }
        public string logoWebAddress { get; set; }
        public string FaviconName { get; set; }
        public string FaviconURL { get; set; }
        public string bussinessName { get; set; }
        public string businessContact { get; set; }
        public string homePageContent { get; set; }
        public string contactUsPageContent { get; set; }
        public string aboutUsPageContent { get; set; }
        public long visits { get; set; }
        public long clicks { get; set; }
        public long search { get; set; }
    }
}
