//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiry
    {
        public long enquiryId { get; set; }
        public string enquiryHtml { get; set; }
        public string fullName { get; set; }
        public string phone { get; set; }
        public string emailAddress { get; set; }
        public string title { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<bool> isNew { get; set; }
    }
}
