//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class featuredCategoryReferrence
    {
        public int featuredCategoryReferrenceId { get; set; }
        public string categoryName { get; set; }
        public string categoryCode { get; set; }
        public int categoryType { get; set; }
        public int cateoryDDlValue { get; set; }
    }
}
