//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPresentStatu
    {
        public long OrderPresentStatusID { get; set; }
        public long OrderId { get; set; }
        public int StatusId { get; set; }
        public string Comment { get; set; }
        public System.DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
    }
}
