//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class packagingInformation
    {
        public int PackagingID { get; set; }
        public string Packaging { get; set; }
        public string ShortDescription { get; set; }
        public System.DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
