//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUWebstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productexcel
    {
        public int productId { get; set; }
        public string name { get; set; }
        public string sku { get; set; }
        public string productTitle { get; set; }
        public string slugURL { get; set; }
        public string productCategory { get; set; }
        public string brand { get; set; }
        public string descriptionHtml { get; set; }
        public string materialHtml { get; set; }
        public string productInformationHtml { get; set; }
        public string imprintInformationHtml { get; set; }
        public string productionHtml { get; set; }
        public string specificationsHtml { get; set; }
        public string ContentsHtml { get; set; }
        public string ShippingHtml { get; set; }
        public string pricingHtml { get; set; }
        public string PoductionHtml { get; set; }
        public string safetyAndCompliance { get; set; }
        public string unit { get; set; }
        public Nullable<bool> isShowPrice { get; set; }
        public string supplier { get; set; }
        public string productImageURL { get; set; }
        public string productVideo { get; set; }
        public string productColor { get; set; }
        public string supplierMobile { get; set; }
        public string supplierEmailAddress { get; set; }
        public string SupplierWebsite { get; set; }
    }
}
